---
abstract: 'Scaling math used in image size constraining (such'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  File::Spec: 0.82
  Test::More: 0.47
distribution_type: module
generated_by: 'Module::Install version 0.76'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Image::Math::Constrain
name: Image-Math-Constrain
no_index:
  directory:
    - inc
    - t
requires:
  perl: 5.005
resources:
  license: http://dev.perl.org/licenses/
version: 1.02
