
no_index: 
  directory: 
    - inc
    - t
generated_by: Module::Install version 0.55
distribution_type: module
version: 1.01
name: Image-Math-Constrain
author: Adam Kennedy <cpan@ali.as>, L<http://ali.as/>
license: perl
build_requires: 
  Test::More: 0.47
  File::Spec: 0.82
requires: 
  perl: 5.005
abstract: Scaling math used in image size constraining (such
